CONSOLE_ENABLE = yes

# HARD OFF for conflicting features:
NKRO_ENABLE = no
FORCE_NKRO = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
MIDI_ENABLE = no
SERIAL_ENABLE = no
STENO_ENABLE = no
VIA_ENABLE = no
NO_USB_STARTUP_CHECK = yes
